/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BankEmployeeRole;

import Business.BankAccount.BankAccount;
import Business.Beneficiary.Beneficiary;
import Business.Enterprise.Enterprise;
import Business.Person.Customer;
import Business.Person.Person;
import Business.Utilities.Utilities;
import UserInterface.CustomerRole.CustomerWorkAreaJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author amitha.murali
 */
public class AddNewBankAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddNewBankAccountJPanel
     */
    private JPanel userProcessContainer;
    private Customer customer;
    private Enterprise enterprise;
    private int routingNumber;
    
    public AddNewBankAccountJPanel(JPanel upc, Customer customer,Enterprise enterprise) {
        initComponents();
        userProcessContainer = upc;        
        this.customer = customer;
        this.enterprise = enterprise;
        routingNumber =  enterprise.getBranchRoutingNumber();
         txtRoutingNumber.setText(String.valueOf(routingNumber));
        JComboBoxAccountType.addItem(BankAccount.Type.Checking);
        JComboBoxAccountType.addItem(BankAccount.Type.Savings);
        
        
    
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        btnAddBankAccount = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        txtBankAccountHolderName = new javax.swing.JTextField();
        lblAccountNumber = new javax.swing.JLabel();
        txtAccountNumber = new javax.swing.JTextField();
        lblRoutingNumber = new javax.swing.JLabel();
        txtRoutingNumber = new javax.swing.JTextField();
        lblInitialBalance = new javax.swing.JLabel();
        txtInitialBalance = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblAccountType = new javax.swing.JLabel();
        JComboBoxAccountType = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHeading.setText("New BankAccount");
        add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, -1, -1));

        btnAddBankAccount.setText("Add Bank Account");
        btnAddBankAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBankAccountActionPerformed(evt);
            }
        });
        add(btnAddBankAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 346, -1, -1));

        btnBack.setText("<<BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 584, -1, -1));

        lblName.setText("Bank Account Holder Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 102, -1, -1));
        add(txtBankAccountHolderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 99, 150, -1));

        lblAccountNumber.setText("Account Number");
        add(lblAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 515, -1, -1));

        txtAccountNumber.setEditable(false);
        txtAccountNumber.setEnabled(false);
        add(txtAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 499, 150, -1));

        lblRoutingNumber.setText("Routing Number");
        add(lblRoutingNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 269, -1, -1));

        txtRoutingNumber.setEditable(false);
        txtRoutingNumber.setEnabled(false);
        add(txtRoutingNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 266, 150, -1));

        lblInitialBalance.setText("Initial Balance");
        add(lblInitialBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 216, -1, -1));
        add(txtInitialBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 213, 151, -1));

        jLabel1.setText("Below fields will be auto generated :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 461, 307, -1));

        lblAccountType.setText("Account Type");
        add(lblAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 156, -1, -1));

        JComboBoxAccountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxAccountTypeActionPerformed(evt);
            }
        });
        add(JComboBoxAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 153, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBankAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBankAccountActionPerformed
        try{
                
                BankAccount.Type accountType = (BankAccount.Type) JComboBoxAccountType.getSelectedItem();                              
            
           if(!txtBankAccountHolderName.getText().isEmpty() && accountType != null && !txtInitialBalance.getText().isEmpty())
            {    
                String bankAccountHolderName = txtBankAccountHolderName.getText();
                String initialAccountBalance = txtInitialBalance.getText();  
                int accountNumber = Utilities.RandomInteger();
               BankAccount bankAccount = customer.getBankAccountDirectory().createBankAccount(accountType,accountNumber, routingNumber);
                if(null != bankAccount)
                {                         
                    bankAccount.setAvailableBalance(Integer.parseInt(initialAccountBalance));
                    bankAccount.setAccountHolderName(bankAccountHolderName);
                    bankAccount.setBankBranch(enterprise.getLocation());
                    JOptionPane.showMessageDialog(null, "Bank Account added successfully!!", "Info", JOptionPane.INFORMATION_MESSAGE);
                    txtAccountNumber.setText(String.valueOf(bankAccount.getAccountNumber()));
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Beneficiary name, Account Number, Routing Number are mandatory fields", "Info", JOptionPane.INFORMATION_MESSAGE);
            }

        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error occured.. Please try later", "Warning", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_btnAddBankAccountActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

       userProcessContainer.remove(this);
        Component [] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length-1];
        ViewCustomerProfileJPanel viewCustomerProfileJPanel = (ViewCustomerProfileJPanel) component;
        viewCustomerProfileJPanel.populateBankAccountsTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void JComboBoxAccountTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxAccountTypeActionPerformed
        // TODO add your handling code here:      
    }//GEN-LAST:event_JComboBoxAccountTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JComboBoxAccountType;
    private javax.swing.JButton btnAddBankAccount;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAccountNumber;
    private javax.swing.JLabel lblAccountType;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblInitialBalance;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRoutingNumber;
    private javax.swing.JTextField txtAccountNumber;
    private javax.swing.JTextField txtBankAccountHolderName;
    private javax.swing.JTextField txtInitialBalance;
    private javax.swing.JTextField txtRoutingNumber;
    // End of variables declaration//GEN-END:variables
}
