/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BankEmployeeRole;

import Business.Enterprise.Enterprise;
import Business.Person.Customer;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amitha.murali
 */
public class ManageCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomerJPanel
     */
    private Enterprise enterprise;
    private JPanel userProcessContainer;
    
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageCustomerJPanel(JPanel userProcessContainer,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;     
        populateTable();
               
    }

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) jTableCustomer.getModel();
        
        model.setRowCount(0);
        
        for (Person person : enterprise.getPersonDirectory().getPersonList()){
            if(person.getPersonType().toString().equals(Person.Type.Customer.getValue()))
            {
            Object[] row = new Object[2];
            row[0] = person.getPersonID();
            row[1] = person;
            model.addRow(row);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDeleteCustomer = new javax.swing.JButton();
        EmployeeListJScrollPane = new javax.swing.JScrollPane();
        jTableCustomer = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        btnViewCustomer = new javax.swing.JButton();
        btnAddCustomer = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDeleteCustomer.setText("Delete Customer Profile");
        btnDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustomerActionPerformed(evt);
            }
        });
        add(btnDeleteCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 210, -1));

        jTableCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        EmployeeListJScrollPane.setViewportView(jTableCustomer);

        add(EmployeeListJScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 192, 670, 110));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, -1, -1));

        btnViewCustomer.setText("View Customer Profile");
        btnViewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCustomerActionPerformed(evt);
            }
        });
        add(btnViewCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 190, -1));

        btnAddCustomer.setText("Add New Customers");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });
        add(btnAddCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 200, -1));

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHeading.setText("Manage Customer Profiles");
        add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustomerActionPerformed
try{
        int row = jTableCustomer.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
       
        Person person = (Person) jTableCustomer.getValueAt(row, 1);
        if(person != null)
        {
        UserAccount userAccount = enterprise.getUserAccountDirectory().searchUserAccountBasedOnPerson(person);
        
        if(userAccount != null)
        {
        enterprise.getUserAccountDirectory().removeUserAccount(userAccount);       
        
        Customer customer = (Customer) jTableCustomer.getValueAt(row, 1);
        if(customer != null)
        {
        enterprise.getPersonDirectory().removeCustomer(customer);
        
        populateTable();
        JOptionPane.showMessageDialog(null, "Customer details deleted successfully!!", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
        }
        }
}
catch(Exception ex)
{
    JOptionPane.showMessageDialog(null, "Error.. Please try later..", "Warning", JOptionPane.WARNING_MESSAGE);
}
    }//GEN-LAST:event_btnDeleteCustomerActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnViewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCustomerActionPerformed

        int row = jTableCustomer.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Person person = (Person)jTableCustomer.getValueAt(row,1);
        ViewCustomerProfileJPanel viewCustomer = new ViewCustomerProfileJPanel(userProcessContainer, person,enterprise);
        userProcessContainer.add("viewCustomer", viewCustomer);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnViewCustomerActionPerformed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed

        AddNewCustomerJPanel addNewCustomerJPanel = new AddNewCustomerJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("addNewCustomer", addNewCustomerJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddCustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane EmployeeListJScrollPane;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnDeleteCustomer;
    private javax.swing.JButton btnViewCustomer;
    private javax.swing.JTable jTableCustomer;
    private javax.swing.JLabel lblHeading;
    // End of variables declaration//GEN-END:variables
}
