/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BankEmployeeRole;


import Business.BankAccount.BankAccount;
import Business.Enterprise.Enterprise;
import Business.Person.Customer;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  amitha.murali
 */
public class ViewCustomerProfileJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCustomerProfileJPanel
     */
     private JPanel userProcessContainer;
     private Enterprise enterprise;
    private Person person;
    private Customer customer;
    
    public ViewCustomerProfileJPanel(JPanel upc, Person person,Enterprise enterprise) {
        initComponents();
        userProcessContainer = upc;
        this.person = person;
        this.enterprise = enterprise;
        customer = (Customer)person;
        txtCustomerName.setText(person.getPersonName());
        txtCustomerId.setText(String.valueOf(person.getPersonID())); 
        txtCustomerAge.setText(String.valueOf(person.getPersonAge()));
        txtCustomerAddress.setText(person.getPersonAddress());
        populateBankAccountsTable();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        lblCustomerID = new javax.swing.JLabel();
        txtCustomerId = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblCustomerAge = new javax.swing.JLabel();
        lblCustomerAddress = new javax.swing.JLabel();
        txtCustomerAddress = new javax.swing.JTextField();
        txtCustomerAge = new javax.swing.JTextField();
        EmployeeListJScrollPane4 = new javax.swing.JScrollPane();
        tblCustomerBankAccounts = new javax.swing.JTable();
        lblBankAccounts = new javax.swing.JLabel();
        btnNewAccount = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHeading.setText("View Customer Details");
        add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        lblCustomerName.setText("Customer Name:");
        add(lblCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 30));

        txtCustomerName.setEditable(false);
        txtCustomerName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 159, -1));

        lblCustomerID.setText("Customer Id:");
        add(lblCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 30));

        txtCustomerId.setEditable(false);
        txtCustomerId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCustomerId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(txtCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 159, -1));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUpdate.setText("Update ");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 110, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, -1, -1));

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 80, 30));

        lblCustomerAge.setText("Customer Age:");
        add(lblCustomerAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        lblCustomerAddress.setText("Customer Address:");
        add(lblCustomerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        txtCustomerAddress.setEditable(false);
        add(txtCustomerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 160, -1));

        txtCustomerAge.setEditable(false);
        txtCustomerAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerAgeActionPerformed(evt);
            }
        });
        add(txtCustomerAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 160, -1));

        tblCustomerBankAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Account no.", "Account Type", "Balance", "Branch"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        EmployeeListJScrollPane4.setViewportView(tblCustomerBankAccounts);

        add(EmployeeListJScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 740, 110));

        lblBankAccounts.setText("Bank Accounts");
        add(lblBankAccounts, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        btnNewAccount.setText("Add Account");
        btnNewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAccountActionPerformed(evt);
            }
        });
        add(btnNewAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 600, 140, -1));

        btnDelete.setText("Delete Account");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 600, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        //txtId.setEditable(true);
        txtCustomerName.setEditable(true);
       // txtCustomerId.setEditable(true);    
        txtCustomerAge.setEditable(true);
        txtCustomerAddress.setEditable(true);
        btnSave.setEnabled(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        backAction();
    }//GEN-LAST:event_btnBackActionPerformed
 public void populateBankAccountsTable(){
        DefaultTableModel model = (DefaultTableModel) tblCustomerBankAccounts.getModel();
        model.setRowCount(0);      
        
        for (BankAccount bankAccount : customer.getBankAccountDirectory().getBankAccountList()){
            
            Object[] row = new Object[4];
            row[0] = bankAccount.getAccountNumber();
            row[1] = bankAccount.getBankAccountType();
            row[2] = bankAccount.getAvailableBalance();
            row[3] = bankAccount;
            model.addRow(row);
            
        }
    }
      private void backAction() {
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageCustomerJPanel manageCustomerJPanel = (ManageCustomerJPanel) component;
        manageCustomerJPanel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }
      
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       // customer.setPersonID(Integer.parseInt(txtCustomerId.getText()));
       try{
       
       if(!txtCustomerName.getText().isEmpty())
       {
           String customerName = txtCustomerName.getText();
        person.setPersonName(customerName);
        person.setPersonAge(Integer.parseInt(txtCustomerAge.getText()));
        person.setPersonAddress(txtCustomerAddress.getText());
        
        JOptionPane.showMessageDialog(null, "Customer details updated successfully!!", "Info", JOptionPane.INFORMATION_MESSAGE);
       
        txtCustomerName.setEditable(false);
      //  txtCustomerId.setEditable(false);  
        txtCustomerAge.setEditable(false);
        txtCustomerAddress.setEditable(false);
        btnSave.setEnabled(false);
       }
       else
       {
            JOptionPane.showMessageDialog(null, "Customer name is mandatory!!", "Info", JOptionPane.INFORMATION_MESSAGE);
       }
       }
       catch(Exception ex)
{
    JOptionPane.showMessageDialog(this, "Please enter proper values for the fields", "Warning", JOptionPane.WARNING_MESSAGE);
    
}
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCustomerAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerAgeActionPerformed

    private void btnNewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAccountActionPerformed
        // TODO add your handling code here:
        AddNewBankAccountJPanel addNewBankAccountJPanel = new AddNewBankAccountJPanel(userProcessContainer, customer,enterprise);
        userProcessContainer.add("addNewBankAccountJPanel", addNewBankAccountJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnNewAccountActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try{
        int row = tblCustomerBankAccounts.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
       
        BankAccount account = (BankAccount) tblCustomerBankAccounts.getValueAt(row, 3);
        if(account != null)
        {        
        customer.getBankAccountDirectory().removeBankAccount(account);       
            
        populateBankAccountsTable();
        JOptionPane.showMessageDialog(null, "Bank Account deleted successfully!!", "Info", JOptionPane.INFORMATION_MESSAGE);
        
        }
}
catch(Exception ex)
{
    JOptionPane.showMessageDialog(null, "Error.. Please try later..", "Warning", JOptionPane.WARNING_MESSAGE);
}
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane EmployeeListJScrollPane4;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNewAccount;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblBankAccounts;
    private javax.swing.JLabel lblCustomerAddress;
    private javax.swing.JLabel lblCustomerAge;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JTable tblCustomerBankAccounts;
    private javax.swing.JTextField txtCustomerAddress;
    private javax.swing.JTextField txtCustomerAge;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtCustomerName;
    // End of variables declaration//GEN-END:variables
}
