/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SecurityOfficierRole;

import Business.Beneficiary.Beneficiary;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.SecurityManagementOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SecurityConcernRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amitha.murali
 */
public class SecurityOfficierWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SecurityOfficierWorkAreaJPanel
     */
      private JPanel userProcessContainer;
    private SecurityManagementOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form SecurityOfficierWorkAreaJPanel
     */
    public SecurityOfficierWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, SecurityManagementOrganization organization, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        populateSecurityConcernTable();
        populateMySecurityConcernTable();
    }

     public void populateSecurityConcernTable(){
        DefaultTableModel model = (DefaultTableModel)tableSecurityConcerns.getModel();
        
        model.setRowCount(0);       
       
        for(WorkRequest request :  organization.getWorkQueue().getWorkRequestList()){
            
            SecurityConcernRequest workRequest = (SecurityConcernRequest) request;
            if(workRequest != null)
            {
                if(workRequest.getStatus().equals(SecurityConcernRequest.OPEN))
                {
            Object[] row = new Object[5];
            row[0] = workRequest.getSender().getPerson().getPersonName();
            row[1] = workRequest.getMessage();
            row[2] = workRequest.getSecuritySeverity().getValue();            
            row[3] = workRequest;
            row[4] = workRequest.getAction();
            
            model.addRow(row);
                }
                
            }
        
        }
    }
     
     public void populateMySecurityConcernTable(){
        DefaultTableModel model = (DefaultTableModel)tableMySecurityConcerns.getModel();
        
        model.setRowCount(0);
       
        for(WorkRequest request :  organization.getWorkQueue().getWorkRequestList()){
            
            SecurityConcernRequest workRequest = (SecurityConcernRequest) request;
            if(workRequest != null)
            {
                 if(workRequest.getStatus().equals(SecurityConcernRequest.PENDING)
                         || workRequest.getStatus().equals(SecurityConcernRequest.RESOLVED)
                         || workRequest.getStatus().equals(SecurityConcernRequest.DEFERRED))
                {
            Object[] row = new Object[5];
            row[0] = workRequest.getSender().getPerson().getPersonName();
            row[1] = workRequest.getMessage();
            row[2] = workRequest.getSecuritySeverity().getValue();            
            row[3] = workRequest;
            row[4] = workRequest.getAction();
            
            model.addRow(row);
                }
                
            }
        
        }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMainHeading = new javax.swing.JLabel();
        btnAssignToMe = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();
        lblHeading1 = new javax.swing.JLabel();
        btnResolved = new javax.swing.JButton();
        btnDeferred = new javax.swing.JButton();
        lbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableMySecurityConcerns = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableSecurityConcerns = new javax.swing.JTable();
        txtComments = new javax.swing.JTextField();
        lblComments = new javax.swing.JLabel();

        lblMainHeading.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblMainHeading.setText("Security Centre");

        btnAssignToMe.setText("Assign to Myself");
        btnAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToMeActionPerformed(evt);
            }
        });

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblHeading.setText("My Work Items");

        lblHeading1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblHeading1.setText("Security Concerns List");

        btnResolved.setText("Resolved");
        btnResolved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResolvedActionPerformed(evt);
            }
        });

        btnDeferred.setText("Deferred");
        btnDeferred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeferredActionPerformed(evt);
            }
        });

        lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Main/Security Centre.png"))); // NOI18N
        lbl.setText("jLabel1");

        tableMySecurityConcerns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "customer", "Security Concern", "Severity", "Status", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableMySecurityConcerns);

        tableSecurityConcerns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "customer", "Security Concern", "Severity", "Status", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableSecurityConcerns);

        lblComments.setText("Comments");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblComments)
                        .addGap(52, 52, 52)
                        .addComponent(txtComments, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                        .addComponent(btnResolved)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeferred))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAssignToMe))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHeading1)
                                    .addComponent(lblHeading)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(lblMainHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(146, 146, 146))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
                    .addGap(143, 143, 143)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl)
                    .addComponent(lblMainHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(lblHeading1)
                .addGap(164, 164, 164)
                .addComponent(btnAssignToMe)
                .addGap(6, 6, 6)
                .addComponent(lblHeading)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResolved)
                    .addComponent(btnDeferred)
                    .addComponent(txtComments, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblComments)))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(203, 203, 203)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(417, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToMeActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableSecurityConcerns.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Select a row", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            SecurityConcernRequest request = (SecurityConcernRequest)tableSecurityConcerns.getValueAt(selectedRow, 3);
            request.setReceiver(userAccount);
            request.setStatus(SecurityConcernRequest.PENDING);
            populateSecurityConcernTable();
            populateMySecurityConcernTable();
            JOptionPane.showMessageDialog(this, "The selected item has been assigned to you", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAssignToMeActionPerformed

    private void btnResolvedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolvedActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableMySecurityConcerns.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Select a row", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            SecurityConcernRequest request = (SecurityConcernRequest)tableMySecurityConcerns.getValueAt(selectedRow, 3);
if(request.getStatus().equals(SecurityConcernRequest.PENDING))
{
            request.setStatus(SecurityConcernRequest.RESOLVED);
            request.setAction(txtComments.getText());
            populateSecurityConcernTable();
            populateMySecurityConcernTable();
           JOptionPane.showMessageDialog(this, "The selected item has been resolved", "Info", JOptionPane.INFORMATION_MESSAGE);
}
else
{
           JOptionPane.showMessageDialog(this, "Sorry you cant take action on these items", "Info", JOptionPane.INFORMATION_MESSAGE);
}
        }
    }//GEN-LAST:event_btnResolvedActionPerformed

    private void btnDeferredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeferredActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableMySecurityConcerns.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Select a row", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            SecurityConcernRequest request = (SecurityConcernRequest)tableMySecurityConcerns.getValueAt(selectedRow, 3);
if(request.getStatus().equals(SecurityConcernRequest.PENDING))
{
            request.setStatus(SecurityConcernRequest.DEFERRED);
            request.setAction(txtComments.getText());
            populateSecurityConcernTable();
            populateMySecurityConcernTable();
             JOptionPane.showMessageDialog(this, "The selected item has been deferred", "Info", JOptionPane.INFORMATION_MESSAGE);
        }else
{
           JOptionPane.showMessageDialog(this, "Sorry you cant take action on these items", "Info", JOptionPane.INFORMATION_MESSAGE);
}
        }
        
    }//GEN-LAST:event_btnDeferredActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignToMe;
    private javax.swing.JButton btnDeferred;
    private javax.swing.JButton btnResolved;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblComments;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblHeading1;
    private javax.swing.JLabel lblMainHeading;
    private javax.swing.JTable tableMySecurityConcerns;
    private javax.swing.JTable tableSecurityConcerns;
    private javax.swing.JTextField txtComments;
    // End of variables declaration//GEN-END:variables
}
