/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.Enterprise.Enterprise;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import Business.Utilities.SendEmail;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author amitha.murali
 */
public class CustomerAuthenticationJPanel extends javax.swing.JPanel {

    
      int generatedOTP = 0;
    /**
     * Creates new form CustomerAuthentication
     */
     JPanel userProcessContainer;
    Enterprise enterprise;
    UserAccount userAccount;
    /** Creates new form AdminWorkAreaJPanel */
    public CustomerAuthenticationJPanel(JPanel userProcessContainer, Enterprise enterprise,UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        lblQuestion.setText(userAccount.getSecurityQuestion());
        txtIPAddress.setText("2601:19b:200:3307:1db6:dae6:f9e8:1ced");
        lblOneTimePassword.setVisible(false);
        txtOneTimePassword.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSecurityQuestion = new javax.swing.JLabel();
        txtSecurityAnswer = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblSecurityAnswer = new javax.swing.JLabel();
        txtIPAddress = new javax.swing.JTextField();
        lblIPaddress = new javax.swing.JLabel();
        lblOneTimePassword = new javax.swing.JLabel();
        txtOneTimePassword = new javax.swing.JTextField();
        lblQuestion = new javax.swing.JLabel();
        lblHeading = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSecurityQuestion.setText("Security Question");
        add(lblSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        add(txtSecurityAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 400, -1));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, -1, -1));

        lblSecurityAnswer.setText("Security Answer");
        add(lblSecurityAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        add(txtIPAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 240, -1));

        lblIPaddress.setText("IP Address");
        add(lblIPaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 90, -1));

        lblOneTimePassword.setText("One Time Password");
        add(lblOneTimePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));
        add(txtOneTimePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 140, -1));

        lblQuestion.setText("Question");
        add(lblQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 390, -1));

        lblHeading.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lblHeading.setText("One last step....");
        add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 370, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
      //   TODO add your handling code here:
        
      
          SendEmail se = null;
        if(!txtSecurityAnswer.getText().isEmpty() && !txtIPAddress.getText().isEmpty())
        {
            String answer = txtSecurityAnswer.getText();
            String myIPAddress = txtIPAddress.getText();
            if(answer.equals(userAccount.getSecurityAnswer()))
            {
                if(userAccount.getWhiteListIPs().contains(myIPAddress))
                {
                    
                    Person person = userAccount.getPerson();
                    CustomerWorkAreaJPanel customerWorkAreaJPanel = new CustomerWorkAreaJPanel(userProcessContainer, enterprise,person,userAccount);
                    userProcessContainer.add("customerWorkAreaJPanel", customerWorkAreaJPanel);
                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
                }else
                {
                    if(generatedOTP > 0)
                    {
                        if(!txtOneTimePassword.getText().equals(String.valueOf(generatedOTP)))
                        {
                            JOptionPane.showMessageDialog(null, "Sorry.. The OTP you entered does not match with the OTP we sent you.. Please try again", "Info", JOptionPane.INFORMATION_MESSAGE);
                        }
                        else
                        {
                            userAccount.getWhiteListIPs().add(myIPAddress);
                            Person person = userAccount.getPerson();
                            CustomerWorkAreaJPanel customerWorkAreaJPanel = new CustomerWorkAreaJPanel(userProcessContainer, enterprise,person,userAccount);
                            userProcessContainer.add("customerWorkAreaJPanel", customerWorkAreaJPanel);
                            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                            layout.next(userProcessContainer);
                            
                        }
                    }else
                    {
                      JOptionPane.showMessageDialog(null, "Sorry.. This machine IP is not registered with us. Could you please enter the OTP sent to you on email for authentication", "Info", JOptionPane.INFORMATION_MESSAGE);
                      lblOneTimePassword.setVisible(true);
                      txtOneTimePassword.setVisible(true);
                      se = new SendEmail(); 
                      
                      if(se == null){
                        } else {
                          generatedOTP = se.generateOTP();
                          JOptionPane.showMessageDialog(null, "Please enter the passcode sent to your registered email id", "Info", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                }
            
                
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Your answer doesnt match.. Please try again!!", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btnSubmitActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblIPaddress;
    private javax.swing.JLabel lblOneTimePassword;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblSecurityAnswer;
    private javax.swing.JLabel lblSecurityQuestion;
    private javax.swing.JTextField txtIPAddress;
    private javax.swing.JTextField txtOneTimePassword;
    private javax.swing.JTextField txtSecurityAnswer;
    // End of variables declaration//GEN-END:variables
}
